import React from "react";
import Head from "next/head";
import styles from "../../../styles/pages/home/Home.module.css";
import Post from "../home/Post";

interface Props {}

export default function index({}: Props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>미정</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Post />
      <Post />
      <Post />
    </div>
  );
}
