import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Post from "../components/pages/home/Post";
import styles from "../styles/pages/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>미정</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Post />
      <Post />
      <Post />
    </div>
  );
};

export default Home;
