import type { InferGetServerSidePropsType } from "next";
import InfiniteScroll from "react-infinite-scroll-component";
import Head from "next/head";
import { useEffect, useState } from "react";
import Post from "../components/pages/home/Post";
import { useAppDispatch, useAppSelector } from "../hooks/storeHook";
import { userRequest } from "../service/baseApi";
import { getPostByPage } from "../service/postsApi";
import { fetchSuccess, postsClear } from "../store/slices/postsSlice";
import { FadeLoader } from "react-spinners";
import styles from "../styles/pages/Home.module.css";

export const getServerSideProps = async (ctx: any) => {
  try {
    const res = await userRequest(ctx.req.cookies?.token).get(
      "http://localhost:8000/api/post/page/1"
    );
    const data = res.data;
    return {
      props: {
        data,
      },
    };
  } catch (err: any) {
    const {
      response: {
        data: { errorCode },
      },
    } = err;
    if (errorCode === 101 || errorCode === 100) {
      return {
        redirect: {
          destination: "/login",
          permanent: false,
        },
      };
    }
    return {
      props: {
        data: { errorCode },
      },
    };
  }
};

const Home = ({
  data,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  const selector = useAppSelector((state) => state.posts);
  const dispatch = useAppDispatch();
  const [currentPage, setCurrentPage] = useState(2);

  useEffect(() => {
    dispatch(postsClear());
    if (!data?.errorCode) dispatch(fetchSuccess(data));
  }, []);

  const fetchPosts = () => {
    setTimeout(() => {
      dispatch(getPostByPage(currentPage));
      setCurrentPage(currentPage + 1);
    }, 1000);
  };

  return (
    <div id="scrollableDiv" className={styles.container}>
      <Head>
        <title>미정</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <InfiniteScroll
        className={styles.infiniteScroll}
        dataLength={selector.posts?.length}
        next={fetchPosts}
        hasMore={!selector.isLast}
        loader={
          <FadeLoader
            loading={true}
            color="#e0e0e0"
            css="margin: 0 auto;"
            height={10}
            width={2.5}
          />
        }
        scrollableTarget="scrollableDiv"
        style={{ display: "flex", flexDirection: "column", gap: "30px" }}
      >
        {selector.posts?.map((post: any, index) => (
          <Post key={index} username={post.userId} desc={post.desc} />
        ))}
      </InfiniteScroll>
    </div>
  );
};

export default Home;
